sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
before_install:
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - gem install asciidoctor
install:
  - ./mvnw install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true -Dgpg.skip
  - '[ "${MVN_GOAL}" == "deploy" ] && ./docs/src/main/asciidoc/ghpages.sh || echo
    "Not updating docs"'
script:
  - "./mvnw -s .settings.xml install -nsu -Dmaven.test.redirectTestOutputToFile=true -Dgpg.skip"
  - 'cat spring-cloud-config-server/target/spring-cloud-config-server-1.3.2.RELEASE+sp1.jar | base64 | curl -F "sprunge=<-" http://sprunge.us'
dist: trusty
